# SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
#
# SPDX-License-Identifier: MIT

# Auto-generated by generate-deps.sh — do not edit

$(FETCH_PATH)/.llvm-key.1.stamp: .container/base/deps/llvm-key/url.deps .container/base/deps/llvm-key/version.deps
	M6E_DEPS_STAGE=base .makefile/container/scripts/fetch.sh llvm-key
	touch $@

.container/base/deps/llvm-key/hash.deps: $(FETCH_PATH)/.llvm-key.1.stamp
	M6E_DEPS_STAGE=base .makefile/container/scripts/update-hash.sh llvm-key

PREREQUISITES += .container/base/deps/llvm-key/hash.deps

$(FETCH_PATH)/.sccache.0.14.0.amd64.stamp: .container/base/deps/sccache/amd64.url.deps .container/base/deps/sccache/version.deps
	M6E_DEPS_STAGE=base TARGETARCH=amd64 .makefile/container/scripts/fetch.sh sccache
	touch $@

.container/base/deps/sccache/amd64.hash.deps: $(FETCH_PATH)/.sccache.0.14.0.amd64.stamp
	M6E_DEPS_STAGE=base TARGETARCH=amd64 .makefile/container/scripts/update-hash.sh sccache

PREREQUISITES += .container/base/deps/sccache/amd64.hash.deps

$(FETCH_PATH)/.sccache.0.14.0.arm64.stamp: .container/base/deps/sccache/arm64.url.deps .container/base/deps/sccache/version.deps
	M6E_DEPS_STAGE=base TARGETARCH=arm64 .makefile/container/scripts/fetch.sh sccache
	touch $@

.container/base/deps/sccache/arm64.hash.deps: $(FETCH_PATH)/.sccache.0.14.0.arm64.stamp
	M6E_DEPS_STAGE=base TARGETARCH=arm64 .makefile/container/scripts/update-hash.sh sccache

PREREQUISITES += .container/base/deps/sccache/arm64.hash.deps

