#!/bin/sh

# SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
#
# SPDX-License-Identifier: MIT

for a in "$@"; do case "$a" in *.s) exec /usr/bin/clang "$@" ;; esac; done
exec ccache /usr/bin/clang "$@"
